apiVersion: apps/v1
kind: Deployment
metadata:
  name: scs-container-service
  namespace: scs-cloud
  labels:
    app: scs-container-service
spec:
  replicas: 1 # due to low resource availability on my local cluster
  selector:
    matchLabels:
      app: scs-container-service
  template:
    metadata:
      labels:
        app: scs-container-service
    spec:
      serviceAccountName: api-access
      containers:
      - name: scs-container-service
        image: suryanshvermaaa/scs-container-service:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        # resources commented out for low resource cluster
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "128Mi"
        #     cpu: "250m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: scs-container-secret
              key: DATABASE_URL
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: scs-container-secret
              key: PORT