kind: Service
apiVersion: v1
metadata:
  name:  scs-container-svc
  namespace:  scs-cloud
spec:
  selector:
    app: scs-container-service
  type:  ClusterIP
  ports:
  - name:  scs-cs-port
    port:  4000
    targetPort:  4000