apiVersion: v1
kind: PersistentVolume
metadata:
  name: scs-container-pv
  namespace: scs-cloud
spec:
  capacity:
    storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/postgres/data