kind: Service
apiVersion: v1
metadata:
  name:  scs-container-db
  namespace: scs-cloud
spec:
  selector:
    name:  scs-container-db
  type:  ClusterIP
  ports:
    - port: 5432
      targetPort: 5432