apiVersion: apps/v1
kind: Deployment
metadata:
  name: scs-hosting-worker
  namespace: scs-cloud
  labels:
    app: scs-hosting-worker
spec:
  replicas: 1 # due to low resource availability on my local cluster
  selector:
    matchLabels:
      app: scs-hosting-worker
  template:
    metadata:
      labels:
        app: scs-hosting-worker
    spec:
      serviceAccountName: api-access
      containers:
      - name: scs-hosting-worker
        image: suryanshvermaaa/scs-hosting-worker:1.0.0
        imagePullPolicy: Always
        # resources commented out for low resource cluster
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "128Mi"
        #     cpu: "250m"
        env:
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: scs-hw-secret
              key: ACCESS_KEY_ID
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: scs-hw-secret
              key: SECRET_ACCESS_KEY
        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: scs-hw-secret
              key: BUCKET_NAME
        - name: QUEUE_HOST
          valueFrom:
            secretKeyRef:
              name: scs-hw-secret
              key: QUEUE_HOST
        - name: QUEUE_USER
          valueFrom:
            secretKeyRef:
              name: scs-hw-secret
              key: QUEUE_USER
        - name: QUEUE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scs-hw-secret
              key: QUEUE_PASSWORD
        - name: QUEUE_PORT
          valueFrom:
            secretKeyRef:
              name: scs-hw-secret
              key: QUEUE_PORT
        - name: HOSTING_DOMAIN
          valueFrom:
            secretKeyRef:
              name: scs-hw-secret
              key: HOSTING_DOMAIN
  