apiVersion: v1
kind: Namespace
metadata:
  name: testing
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: testing1234-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/devservice/testing1234
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testing1234-pvc
  namespace: testing
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: testing1234-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing1234
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
        - name: testing1234
          image: suryanshvermaaa/vs-code:1.0.0
          ports:
            - containerPort: 6901
          env:
            - name: VNC_PW
              value: "suryansh"
          volumeMounts:
            - name: testing1234-data
              mountPath: /home/kasm-user
      volumes:
        - name: testing1234-data
          persistentVolumeClaim:
            claimName: testing1234-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: testing1234
  namespace: testing
spec:
  selector:
    app: testing
  ports:
    - protocol: TCP
      port: 6901
      targetPort: 6901
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing1234
  namespace: testing
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
spec:
  rules:
    - host: testing.suryanshverma.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testing1234
                port:
                  number: 6901
